name: Toto en vacance
on: [push]
jobs: 
  Tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Recup du repo 
        uses: actions/checkout@v3
      - name: test 1
        run: echo 1
      - name: test 2
        run: echo "test 2"
  Build: 
    needs: [Tests]
    runs-on: ubuntu-latest
    steps:
      - name: Je Build
        run: echo "Je BuilD...."
  Check: 
    needs: [Tests, Build]
    runs-on: ubuntu-latest
    if: always() && (needs.Tests.result == 'failure' || needs.Build.result == 'failure')
    steps: 
      - name: "Mail"
        run: echo "mail"
