name: Toto en vacance
on: [push]
jobs: 
  Tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Recup du repo 
        uses: actions/checkout@v3
      - name: test 1
        run: echo "je test"
      - name: test 2
        run: echo "test 2"
      - name: Envoi mail
        if: ${{ failure() }}
        run: echo "Envoi d'un email si le test echoue"
  # Build: 
  #   needs: [Tests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Je Build
  #       run: echo "Je BuilD...."