name: Toto en vacance
on: [push]
jobs: 
  MonPremierJob: 
    runs-on: ubuntu-latest
    steps:
      - name: Recup du repo 
        uses: actions/checkout@v3
        with:
          ref: "refs/tags/2.0.0"
      - name: affichez le contenu de mon job
        run: ls